-- SkillForge — extension de la banque de questions (V2)
-- Ajoute 6 questions par famille (2 par niveau de difficulté) aux 24
-- questions du seed initial, portant le total à 48. Fichier séparé du
-- seed.sql d'origine car celui-ci recrée les catégories (contrainte
-- UNIQUE sur slug) — à exécuter une seule fois après le seed initial.

-- IA & ML
INSERT INTO questions (category_id, difficulty, prompt, rubric, hint, resources) VALUES
  ((SELECT id FROM categories WHERE slug='ia-ml'), 1,
   'Qu''est-ce qu''un token dans le contexte d''un LLM, et pourquoi la tarification et les limites de contexte se comptent-elles en tokens plutôt qu''en mots ?',
   '["token = unité de découpage du texte (sous-mot, pas toujours un mot entier)", "un mot peut correspondre à plusieurs tokens selon la langue/rareté", "explique pourquoi c''est une unité plus stable pour mesurer coût/contexte"]',
   'Un mot rare ou composé peut être découpé en plusieurs morceaux — pensez à l''unité que le modèle manipule réellement.',
   '[{"type":"article","title":"What are tokens? — Anthropic Docs","url":"https://docs.anthropic.com/en/docs/resources/glossary"},{"type":"video","title":"Vidéos sur les tokens en NLP","url":"https://www.youtube.com/results?search_query=tokenization+LLM+expliqu%C3%A9"}]'),
  ((SELECT id FROM categories WHERE slug='ia-ml'), 1,
   'Quelle est la différence entre un modèle génératif et un modèle discriminatif ?',
   '["génératif = apprend à produire/générer des données ressemblant aux données d''entraînement", "discriminatif = apprend à séparer/classer des données selon des catégories", "donne un exemple pour chacun"]',
   'L''un cherche à créer du contenu nouveau, l''autre à trancher entre des catégories existantes.',
   '[{"type":"article","title":"Generative vs discriminative models — Wikipédia (EN)","url":"https://en.wikipedia.org/wiki/Generative_model"},{"type":"video","title":"Vidéos sur modèle génératif vs discriminatif","url":"https://www.youtube.com/results?search_query=generative+vs+discriminative+model+expliqu%C3%A9"}]'),
  ((SELECT id FROM categories WHERE slug='ia-ml'), 2,
   'Qu''est-ce que le fine-tuning et en quoi diffère-t-il du prompt engineering pour adapter un LLM à un cas d''usage ?',
   '["fine-tuning = ré-entraînement des poids du modèle sur un jeu de données spécifique", "prompt engineering = adaptation par l''instruction, sans toucher aux poids", "compare coût, flexibilité et cas d''usage de chaque approche"]',
   'L''un modifie durablement le modèle lui-même, l''autre change seulement ce qu''on lui demande au moment de l''appel.',
   '[{"type":"article","title":"Fine-tuning — Anthropic Docs","url":"https://docs.anthropic.com/en/docs/resources/glossary"},{"type":"video","title":"Vidéos sur fine-tuning vs prompt engineering","url":"https://www.youtube.com/results?search_query=fine+tuning+vs+prompt+engineering"}]'),
  ((SELECT id FROM categories WHERE slug='ia-ml'), 2,
   'Expliquez la notion de température dans la génération de texte par un LLM, et son effet sur les réponses.',
   '["paramètre qui contrôle le caractère aléatoire/déterministe de la génération", "température basse = réponses plus prévisibles/conservatrices, haute = plus créatives/variées", "cite un cas d''usage pour chaque extrême (ex: code vs brainstorming)"]',
   'Pensez à ce qui change entre une réponse toujours identique à la même question et une réponse différente à chaque fois.',
   '[{"type":"article","title":"LLM parameters — Anthropic Docs","url":"https://docs.anthropic.com/en/api/messages"},{"type":"video","title":"Vidéos sur la température des LLM","url":"https://www.youtube.com/results?search_query=temperature+LLM+expliqu%C3%A9e"}]'),
  ((SELECT id FROM categories WHERE slug='ia-ml'), 3,
   'Comment concevriez-vous un pipeline d''évaluation continue (eval set) pour surveiller la qualité d''un produit basé sur un LLM en production ?',
   '["jeu de données de test représentatif, régulièrement mis à jour", "métriques automatiques (LLM-as-judge, règles) ET échantillonnage humain", "détection de régression avant chaque déploiement de prompt/modèle", "suivi dans le temps, pas seulement au lancement"]',
   'Pensez à ce qui doit se passer AVANT de déployer un changement de prompt ou de modèle, pas seulement après coup.',
   '[{"type":"article","title":"Evaluating AI systems — Anthropic Docs","url":"https://docs.anthropic.com/en/docs/build-with-claude/develop-tests"},{"type":"video","title":"Vidéos sur l''évaluation continue des LLM","url":"https://www.youtube.com/results?search_query=LLM+evaluation+pipeline+production"}]'),
  ((SELECT id FROM categories WHERE slug='ia-ml'), 3,
   'Quels compromis entre latence, coût et qualité arbitrez-vous en choisissant la taille d''un modèle pour un cas d''usage donné ?',
   '["un modèle plus grand est généralement plus précis mais plus lent et plus cher", "certaines tâches simples n''ont pas besoin du modèle le plus puissant", "propose une approche (routage selon la complexité, modèle plus petit + vérification)"]',
   'Toutes les tâches n''ont pas besoin du modèle le plus puissant disponible — comment décideriez-vous au cas par cas ?',
   '[{"type":"article","title":"Choosing a model — Anthropic Docs","url":"https://docs.anthropic.com/en/docs/about-claude/models"},{"type":"video","title":"Vidéos sur le choix de taille de modèle LLM","url":"https://www.youtube.com/results?search_query=choisir+taille+mod%C3%A8le+LLM+co%C3%BBt+latence"}]')
;

-- Gestion de projet digital
INSERT INTO questions (category_id, difficulty, prompt, rubric, hint, resources) VALUES
  ((SELECT id FROM categories WHERE slug='gestion-projet'), 1,
   'Qu''est-ce qu''un daily stand-up et à quoi sert-il concrètement dans une équipe agile ?',
   '["réunion courte et quotidienne de synchronisation d''équipe", "chacun partage ce qu''il a fait, va faire, et les blocages", "objectif : détecter les blocages tôt, pas un reporting descendant"]',
   'C''est un point de synchronisation entre pairs, pas un rapport à un supérieur — quelle différence ça fait sur sa forme ?',
   '[{"type":"article","title":"Le daily scrum — Atlassian","url":"https://www.atlassian.com/fr/agile/scrum/standups"},{"type":"video","title":"Vidéos sur le daily stand-up","url":"https://www.youtube.com/results?search_query=daily+stand+up+agile+expliqu%C3%A9"}]'),
  ((SELECT id FROM categories WHERE slug='gestion-projet'), 1,
   'Quelle est la différence entre un livrable et un jalon (milestone) dans un projet ?',
   '["livrable = un résultat concret produit (document, fonctionnalité, rapport)", "jalon = un point de repère temporel marquant une étape importante", "un jalon peut être associé à un ou plusieurs livrables, mais ce n''est pas la même chose"]',
   'L''un est une chose que vous produisez, l''autre est un moment dans le temps.',
   '[{"type":"article","title":"Jalon (gestion de projet) — Wikipédia","url":"https://fr.wikipedia.org/wiki/Jalon_(gestion_de_projet)"},{"type":"video","title":"Vidéos sur livrables et jalons projet","url":"https://www.youtube.com/results?search_query=livrable+vs+jalon+gestion+de+projet"}]'),
  ((SELECT id FROM categories WHERE slug='gestion-projet'), 2,
   'Comment gérez-vous un désaccord entre deux membres de l''équipe sur le choix d''une solution technique ?',
   '["fait émerger les critères de décision objectifs (coût, délai, maintenabilité) plutôt que trancher par autorité", "encourage l''argumentation factuelle plutôt que la préférence personnelle", "propose un mécanisme de décision (POC, avis d''un tiers, decision record) si le blocage persiste"]',
   'Cherchez d''abord à rendre les critères de décision explicites avant de trancher qui a "raison".',
   '[{"type":"article","title":"Architecture Decision Records — Martin Fowler","url":"https://martinfowler.com/articles/document-architecture-decisions.html"},{"type":"video","title":"Vidéos sur la gestion des désaccords techniques en équipe","url":"https://www.youtube.com/results?search_query=g%C3%A9rer+d%C3%A9saccord+technique+%C3%A9quipe"}]'),
  ((SELECT id FROM categories WHERE slug='gestion-projet'), 2,
   'Qu''est-ce que la vélocité d''une équipe agile et à quoi sert-elle concrètement ?',
   '["mesure de la quantité de travail livrée par sprint (souvent en points de complexité)", "sert à planifier la capacité des sprints suivants, pas à comparer les équipes entre elles", "attention aux dérives : ce n''est pas un indicateur de performance individuelle"]',
   'C''est un outil de planification pour UNE équipe dans le temps — pas une note de performance.',
   '[{"type":"article","title":"Vélocité — Atlassian","url":"https://www.atlassian.com/fr/agile/scrum/velocity"},{"type":"video","title":"Vidéos sur la vélocité en agile","url":"https://www.youtube.com/results?search_query=v%C3%A9locit%C3%A9+agile+scrum+expliqu%C3%A9e"}]'),
  ((SELECT id FROM categories WHERE slug='gestion-projet'), 3,
   'Vous devez annoncer un retard important à un client stratégique. Comment préparez-vous cette communication ?',
   '["anticipe et communique dès que le risque est identifié, pas au dernier moment", "prépare les causes, l''impact chiffré, et un plan d''action concret avant l''annonce", "propose des options (réduction de scope, ressources supplémentaires, nouvelle date) plutôt qu''une simple excuse", "adapte le ton à l''interlocuteur (factuel, sans dramatiser ni minimiser)"]',
   'Ne venez jamais annoncer un problème sans apporter au moins une piste de solution avec.',
   '[{"type":"article","title":"Communiquer un risque projet — PMI (EN)","url":"https://www.pmi.org/learning/library"},{"type":"video","title":"Vidéos sur l''annonce d''un retard projet à un client","url":"https://www.youtube.com/results?search_query=annoncer+un+retard+de+projet+%C3%A0+un+client"}]'),
  ((SELECT id FROM categories WHERE slug='gestion-projet'), 3,
   'Comment structurez-vous un post-mortem de projet pour qu''il soit réellement utile aux projets suivants ?',
   '["se concentre sur les faits et processus, pas sur la recherche de coupables", "distingue ce qui a bien fonctionné de ce qui doit changer", "aboutit à des actions concrètes et assignées, pas seulement à un constat", "les enseignements sont documentés et réellement réutilisés (pas un rapport qui dort)"]',
   'Un post-mortem sans actions assignées à quelqu''un ne sert généralement à rien — comment évitez-vous ça ?',
   '[{"type":"article","title":"How to run a postmortem — Atlassian","url":"https://www.atlassian.com/incident-management/postmortem"},{"type":"video","title":"Vidéos sur le post-mortem de projet","url":"https://www.youtube.com/results?search_query=post+mortem+projet+retour+d%27exp%C3%A9rience"}]')
;

-- Développement web
INSERT INTO questions (category_id, difficulty, prompt, rubric, hint, resources) VALUES
  ((SELECT id FROM categories WHERE slug='dev-web'), 1,
   'Qu''est-ce que le DOM et comment un navigateur l''utilise-t-il pour afficher une page web ?',
   '["DOM = représentation en arbre du document HTML en mémoire", "le navigateur le construit en parsant le HTML puis l''utilise pour le rendu", "JavaScript peut le manipuler dynamiquement pour changer la page sans recharger"]',
   'Pensez à la structure en arbre que le navigateur construit à partir de votre fichier HTML avant de l''afficher.',
   '[{"type":"article","title":"Introduction to the DOM — MDN","url":"https://developer.mozilla.org/fr/docs/Web/API/Document_Object_Model/Introduction"},{"type":"video","title":"Vidéos sur le DOM","url":"https://www.youtube.com/results?search_query=qu%27est+ce+que+le+DOM+expliqu%C3%A9"}]'),
  ((SELECT id FROM categories WHERE slug='dev-web'), 1,
   'Quelle est la différence entre HTTP et HTTPS ?',
   '["HTTPS = HTTP chiffré via TLS/SSL entre client et serveur", "protège la confidentialité et l''intégrité des données échangées", "mentionne un risque concret d''utiliser du HTTP non chiffré (interception, altération)"]',
   'Le "S" ajoute une couche de chiffrement — que pourrait intercepter quelqu''un sur le réseau sans elle ?',
   '[{"type":"article","title":"HTTPS — MDN","url":"https://developer.mozilla.org/fr/docs/Glossary/HTTPS"},{"type":"video","title":"Vidéos sur HTTP vs HTTPS","url":"https://www.youtube.com/results?search_query=HTTP+vs+HTTPS+expliqu%C3%A9"}]'),
  ((SELECT id FROM categories WHERE slug='dev-web'), 2,
   'Qu''est-ce que le CORS et pourquoi les navigateurs l''imposent-ils ?',
   '["Cross-Origin Resource Sharing : mécanisme qui autorise ou bloque les requêtes entre origines différentes", "protection contre certaines attaques exploitant les cookies/sessions d''un autre site", "le serveur doit explicitement autoriser les origines via des en-têtes HTTP"]',
   'Sans cette protection, un site malveillant pourrait faire des requêtes en votre nom vers un autre site où vous êtes connecté.',
   '[{"type":"article","title":"CORS — MDN","url":"https://developer.mozilla.org/fr/docs/Web/HTTP/CORS"},{"type":"video","title":"Vidéos sur le CORS","url":"https://www.youtube.com/results?search_query=CORS+expliqu%C3%A9+simplement"}]'),
  ((SELECT id FROM categories WHERE slug='dev-web'), 2,
   'Comment optimiseriez-vous le temps de chargement initial d''une page web ?',
   '["réduit la taille des ressources (minification, compression, images optimisées)", "charge en priorité le contenu visible (lazy loading pour le reste)", "utilise un CDN et le cache navigateur pour réduire la latence réseau", "limite le JavaScript bloquant le rendu initial"]',
   'Distinguez ce que l''utilisateur doit voir immédiatement de ce qui peut attendre quelques instants de plus.',
   '[{"type":"article","title":"Web performance — MDN","url":"https://developer.mozilla.org/fr/docs/Web/Performance"},{"type":"video","title":"Vidéos sur l''optimisation du temps de chargement web","url":"https://www.youtube.com/results?search_query=optimiser+temps+de+chargement+page+web"}]'),
  ((SELECT id FROM categories WHERE slug='dev-web'), 3,
   'Comment concevriez-vous un système de cache à plusieurs niveaux (navigateur, CDN, serveur) pour une application à fort trafic ?',
   '["distingue la durée de vie et la stratégie d''invalidation propre à chaque niveau", "identifie ce qui peut être caché sans risque (contenu statique) vs ce qui ne peut pas (données sensibles/personnalisées)", "aborde la cohérence lors d''une mise à jour de contenu (invalidation, versioning)"]',
   'Chaque niveau de cache a une durée de vie et un problème d''invalidation différents — comment les faire cohabiter sans servir du contenu périmé ?',
   '[{"type":"article","title":"Caching — Cloudflare Learning","url":"https://www.cloudflare.com/fr-fr/learning/cdn/what-is-caching/"},{"type":"video","title":"Vidéos sur les architectures de cache multi-niveaux","url":"https://www.youtube.com/results?search_query=multi+level+caching+architecture+CDN"}]'),
  ((SELECT id FROM categories WHERE slug='dev-web'), 3,
   'Quels choix architecturaux feriez-vous pour garantir la haute disponibilité d''une API critique ?',
   '["élimine les points de défaillance unique (redondance, plusieurs régions/zones)", "prévoit des mécanismes de repli (retry, circuit breaker, dégradation gracieuse)", "surveille activement (monitoring, alerting) plutôt que de découvrir la panne via les utilisateurs", "teste réellement la résilience (chaos engineering, tests de charge)"]',
   'Pensez à ce qui se passe quand UNE dépendance tombe — le système doit-il tomber entièrement avec elle ?',
   '[{"type":"article","title":"High availability — Cloudflare Learning","url":"https://www.cloudflare.com/learning/performance/what-is-high-availability/"},{"type":"video","title":"Vidéos sur la haute disponibilité d''une API","url":"https://www.youtube.com/results?search_query=high+availability+API+architecture"}]')
;

-- Culture métiers du numérique
INSERT INTO questions (category_id, difficulty, prompt, rubric, hint, resources) VALUES
  ((SELECT id FROM categories WHERE slug='culture-num'), 1,
   'Qu''est-ce qu''un MVP (Minimum Viable Product) et à quoi sert-il ?',
   '["version minimale d''un produit qui permet de tester une hypothèse avec de vrais utilisateurs", "objectif : apprendre vite avec un investissement limité, pas livrer un produit incomplet au rabais", "cite le lien avec le principe "build-measure-learn""]',
   'Ce n''est pas "un produit pas fini" — c''est un outil pour apprendre le plus vite possible avec le moins d''efforts.',
   '[{"type":"article","title":"Minimum viable product — Wikipédia","url":"https://fr.wikipedia.org/wiki/Produit_minimum_viable"},{"type":"video","title":"Vidéos sur le MVP","url":"https://www.youtube.com/results?search_query=MVP+minimum+viable+product+expliqu%C3%A9"}]'),
  ((SELECT id FROM categories WHERE slug='culture-num'), 1,
   'Quelle est la différence entre B2B et B2C dans le numérique, et en quoi cela influence-t-il un produit digital ?',
   '["B2B = vente à d''autres entreprises, B2C = vente directe aux consommateurs", "cycles de décision, nombre d''utilisateurs et exigences différentes (ex: intégrations, support vs simplicité, volume)", "donne un exemple d''impact concret sur le design ou la stratégie produit"]',
   'Pensez à qui décide de l''achat, et si c''est la même personne qui utilise réellement le produit au quotidien.',
   '[{"type":"article","title":"B2B vs B2C — Wikipédia (EN)","url":"https://en.wikipedia.org/wiki/Business-to-business"},{"type":"video","title":"Vidéos sur B2B vs B2C","url":"https://www.youtube.com/results?search_query=B2B+vs+B2C+diff%C3%A9rence+expliqu%C3%A9e"}]'),
  ((SELECT id FROM categories WHERE slug='culture-num'), 2,
   'Comment mesureriez-vous la satisfaction utilisateur d''un produit digital ?',
   '["combine des indicateurs quantitatifs (NPS, CSAT, taux de rétention/churn) et qualitatifs (entretiens, retours)", "évite de se fier à un seul chiffre isolé sans contexte", "relie la mesure à des actions concrètes d''amélioration, pas juste un tableau de bord"]',
   'Un seul chiffre (comme le NPS) ne raconte jamais toute l''histoire — que faut-il croiser avec ?',
   '[{"type":"article","title":"Net Promoter Score — Wikipédia","url":"https://fr.wikipedia.org/wiki/Net_Promoter_Score"},{"type":"video","title":"Vidéos sur la mesure de la satisfaction utilisateur","url":"https://www.youtube.com/results?search_query=mesurer+satisfaction+utilisateur+produit+digital"}]'),
  ((SELECT id FROM categories WHERE slug='culture-num'), 2,
   'Qu''est-ce que l''accessibilité numérique et pourquoi est-elle importante pour un produit digital ?',
   '["conception permettant l''usage du produit par des personnes en situation de handicap (visuel, moteur, cognitif...)", "enjeu à la fois éthique, légal (obligations RGAA/WCAG) et business (audience élargie)", "cite un exemple concret de bonne pratique (contraste, navigation clavier, alternatives texte)"]',
   'Pensez à quelqu''un qui ne peut pas utiliser une souris, ou qui ne voit pas les couleurs de la même façon que vous.',
   '[{"type":"article","title":"Accessibilité web — MDN","url":"https://developer.mozilla.org/fr/docs/Web/Accessibility"},{"type":"video","title":"Vidéos sur l''accessibilité numérique","url":"https://www.youtube.com/results?search_query=accessibilit%C3%A9+num%C3%A9rique+expliqu%C3%A9e"}]'),
  ((SELECT id FROM categories WHERE slug='culture-num'), 3,
   'Comment un product manager priorise-t-il une roadmap avec des ressources limitées et des demandes concurrentes ?',
   '["s''appuie sur un cadre de priorisation explicite (valeur/effort, RICE, alignement stratégique)", "arbitre entre demandes court terme (clients, support) et vision produit long terme", "communique les choix et leurs raisons aux parties prenantes, y compris ce qui n''est PAS priorisé", "reste capable de réviser la roadmap si de nouvelles informations arrivent"]',
   'Le plus dur n''est souvent pas de dire oui, mais d''expliquer clairement pourquoi on dit non à une demande légitime.',
   '[{"type":"article","title":"RICE scoring model — Intercom (EN)","url":"https://www.intercom.com/blog/rice-simple-prioritization-for-product-managers/"},{"type":"video","title":"Vidéos sur la priorisation de roadmap produit","url":"https://www.youtube.com/results?search_query=priorisation+roadmap+produit+RICE"}]'),
  ((SELECT id FROM categories WHERE slug='culture-num'), 3,
   'Quels risques et opportunités l''IA générative pose-t-elle pour les métiers du numérique dans les prochaines années ?',
   '["opportunités : productivité accrue, nouveaux produits/services, automatisation de tâches répétitives", "risques : dépendance à des fournisseurs tiers, désinformation, transformation rapide de certains métiers", "aborde la nécessité de monter en compétence plutôt que de subir le changement", "évite le double écueil du catastrophisme et de la naïveté technologique"]',
   'Évitez les deux extrêmes faciles ("tout va disparaître" ou "ça ne changera rien") — quelle position nuancée pouvez-vous défendre ?',
   '[{"type":"article","title":"Future of work and AI — CNIL","url":"https://www.cnil.fr/fr/intelligence-artificielle"},{"type":"video","title":"Vidéos sur l''IA générative et l''avenir des métiers du numérique","url":"https://www.youtube.com/results?search_query=IA+g%C3%A9n%C3%A9rative+avenir+des+m%C3%A9tiers+du+num%C3%A9rique"}]')
;
